### ISSUE TITLE
Appearance => OS,  does not work on Mac OS

### ISSUE THREAD

**Issue by SamuelRott** [radio4000/components#103]
System theme is set to dark but when in `r4-color-scheme` `OS` is selected, R4 theme is "light".

Other then that switching  in `r4-color-scheme` from dark to light works as expected.

In screen shot you can see that OS theme is dark and working as expected in chrome.

<img width="1440" alt="Screenshot 2023-08-07 at 13 13 05" src="https://github.com/radio4000/components/assets/12135011/c6732160-539c-4547-a7ff-52f57967538d">

**Comment by oskarrough** [comment]
Thanks! I really wanted to not have to do dark mode. It's one of those things, "ah easy let's change white to black" and done. But it's not like that 🗡️ 

- different shades of grey
- managing local user pref vs browser pref vs os pref
- manage local pref vs the one stored in remote db

The way it's currently implemented is more or less
1. is a theme stored in local storage? use it
2. load them from authenticated user's preferences, use it and update local storage
3. no theme? look at browser preferences

Happy to discard any code when we can fix bugs and make it simpler!

## Relevant code 

This piece runs on every page. The logic must be wrong.

- https://github.com/radio4000/components/blob/main/src/components/r4-app.js#L136-L150

This is the component you see on /settings

- https://github.com/radio4000/components/blob/main/src/components/r4-color-scheme.js#L30-L43

**Comment by oskarrough** [comment]
Fixed by @4www in recent commits
