### ISSUE TITLE
refactor app menu into r4-menu, so it can do "active link"

### ISSUE THREAD

**Issue by 4www** [radio4000/components#114]

**Comment by oskarrough** [comment]
Should we just compare the new URL(window.location).href with the href of the links?

**Comment by oskarrough** [comment]
I tried with this

```js
get activePath() {
  const url = new URL(window.location)
  return url.pathname.replace(this.href.replace(url.origin, ''), '')
}
```

```html
<li>
  <a ?active=${this.activePath === '/settings'} href=${this.href + '/settings'}>Go to settings</a>
</li>
```

it works, but the `<r4-app-menu>` is not re-rendered whenever the route changes. How do we do this again?

**Comment by oskarrough** [comment]
Can continue in this PR if someone has an idea https://github.com/radio4000/components/pull/149
