### ISSUE TITLE
Add channel-actions on the channels list (for quick access to things)

### ISSUE THREAD

**Issue by 4www** [radio4000/components#115]

**Comment by oskarrough** [comment]
We used to have a `<select>` for this. Maybe we can use (or get inspired) by https://github.com/github/details-menu-element instead. Has the advantage that we can use real links, and we can style it to fit.

**Comment by oskarrough** [comment]
https://github.com/radio4000/components/pull/137 attempts to solve this by adding a dropdown menu to the track list item.

**Comment by oskarrough** [comment]
@4www I merged it.

- Styles are in index.css (for all themes)
- Please remove/refactor/edit as we please
