### ISSUE TITLE
give a URL param for search tracks

### ISSUE THREAD

**Issue by 4www** [radio4000/components#120]

**Comment by oskarrough** [comment]
would be nice if we had

- /:slug/tracks/?search=ringring

but we have

- https://beta.radio4000.com/oskar/tracks?page=1&limit=10&filters=%5B%7B%22column%22:%22fts%22,%22operator%22:%22textSearch%22,%22value%22:%22%27ring+ring%27:*%22%7D%5D&orderBy=created_at&orderConfig=%7B%22ascending%22:false%7D

which works as well
