### ISSUE TITLE
fix player display of track list

### ISSUE THREAD

**Issue by 4www** [radio4000/components#126]

**Comment by oskarrough** [comment]
When the player is fixed to the side, we can make it full height and show the track list.

When the player is docked to the bottom or top, I don't see how we can show it, unless we make some new track list overlay/panel thing outside of `<radio4000-player>`.

**Comment by oskarrough** [comment]
Now it's full height on larger screens, but only when maximized. It's reliant on the height of the layout-control buttons, but that seems ok for now.
