### ISSUE TITLE
Fix bookmarklet

### ISSUE THREAD

**Issue by 4www** [radio4000/components#130]

**Comment by oskarrough** [comment]
Just adding to this, in v1 we offered a bookmarklet to add tracks.

In v2 we don't offer it any longer, but we could. Do people use bookmarklets still?
Personally I've just bookmarked radio4000.com/add, and am happy with that.

If someone wants the bookmarket back, please re-open!

**Comment by 4www** [comment]
https://github.com/internet4000/radio4000/blob/master/app/components/bookmarklet-link/template.hbs

Think we can add it again, does look like it still works?
