### ISSUE TITLE
r4-player "modes" (fullscreen, docked, small etc.)

### ISSUE THREAD

**Issue by oskarrough** [radio4000/components#29]

**Comment by user-09876** [comment]
should this be in the `radio400-player`?

Advantages:
- sites & people using the radio4000-player, can benefit of the multiple visual aspects
- don't have to re-implement it in each app we want to use the player and offer different visual modes

Inconvenients:
- how does it behave if there are multiple players in a page? (mix.r4.com etc.)
- does the player need to send "visual mode" events, so the above app can catch it up?
- does a parent app need to adapt to the player modes?

**Comment by oskarrough** [comment]
You've played with this more than I have. Are the modes currently in the player or ember app?

If radio4000-player is responsive enough (with css), maybe it doesn't need to know about any "modes" and it's up to whatever parent website/app you have?
